/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionId = IDL.Nat;
export const PinCode = IDL.Text;
export const SessionStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
});
export const Time = IDL.Int;
export const Session = IDL.Record({
  'id' : SessionId,
  'pin' : PinCode,
  'status' : SessionStatus,
  'title' : IDL.Text,
  'attendeeCount' : IDL.Nat,
  'createdAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AttendanceId = IDL.Nat;
export const Attendance = IDL.Record({
  'id' : AttendanceId,
  'name' : IDL.Text,
  'timestamp' : Time,
  'sessionId' : SessionId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeSession' : IDL.Func([SessionId], [], []),
  'createSession' : IDL.Func([IDL.Text], [SessionId], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSessionAttendees' : IDL.Func(
      [SessionId],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAttendance' : IDL.Func([IDL.Text, PinCode], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionId = IDL.Nat;
  const PinCode = IDL.Text;
  const SessionStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
  });
  const Time = IDL.Int;
  const Session = IDL.Record({
    'id' : SessionId,
    'pin' : PinCode,
    'status' : SessionStatus,
    'title' : IDL.Text,
    'attendeeCount' : IDL.Nat,
    'createdAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AttendanceId = IDL.Nat;
  const Attendance = IDL.Record({
    'id' : AttendanceId,
    'name' : IDL.Text,
    'timestamp' : Time,
    'sessionId' : SessionId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeSession' : IDL.Func([SessionId], [], []),
    'createSession' : IDL.Func([IDL.Text], [SessionId], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSessionAttendees' : IDL.Func(
        [SessionId],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAttendance' : IDL.Func([IDL.Text, PinCode], [], []),
  });
};

export const init = ({ IDL }) => { return []; };